components:
  schemas:
    Service:
      type: object
      properties:
        id:
          type: string
          format: uuid
        owner_id:
          type: string
          format: uuid
        name:
          type: string
        price:
          type: number
        #        location:
        #          type: string
        comment:
          type: string
        prev_service_id:
          type: string
          format: uuid
        active:
          type: boolean
        created_at:
          type: string
          format: date-time
    #      required:
    #        - owner_id
    #        - name
    #        - price
    #        - comment
    #        - active
    ServiceList:
      type: array
      items:
        $ref: '#/components/schemas/Service'
    ServiceCreate:
      type: object
      properties:
        owner_id:
          type: string
          format: uuid
        name:
          type: string
        price:
          type: number
        #location:
        #  type: string
      required:
        - owner_id
        - name
        - price
    ServiceUpdate:
      type: object
      properties:
        name:
          type: string
        price:
          type: number
        #location:
        #  type: string
    ServiceListSuccessResponse:
      type: object
      properties:
        services:
          $ref: '#/components/schemas/ServiceList'
        message:
          type: string
    ServiceListErrorResponse:
      type: object
      properties:
        services:
          type: array
        message:
          type: string
