components:
  schemas:
    Service:
      type: object
      properties:
        id:
          type: string
          format: uuid
        userID:
          type: string
          format: uuid
        name:
          type: string
        price:
          type: number
        #        location:
        #          type: string
        comment:
          type: string
        prevServiceID:
          type: string
          format: uuid
        active:
          type: boolean
        createdAt:
          type: string
          format: date-time
        dynamicPrices:
          type: array
          items:
            $ref: './dynamic_price.yaml#/components/schemas/DynamicPrice'
    ServiceOnly:
      type: object
      properties:
        id:
          type: string
          format: uuid
        userID:
          type: string
          format: uuid
        name:
          type: string
        price:
          type: number
        #        location:
        #          type: string
        comment:
          type: string
        prevServiceID:
          type: string
          format: uuid
        active:
          type: boolean
        createdAt:
          type: string
          format: date-time
    ServiceList:
      type: array
      items:
        $ref: '#/components/schemas/Service'
    ServiceCreate:
      type: object
      properties:
        name:
          type: string
        price:
          type: number
        comment:
          type: string
        #location:
        #  type: string
        dynamicPrices:
          type: array
          items:
            $ref: './dynamic_price.yaml#/components/schemas/DynamicPriceCreateUpdate'
      required:
        - name
        - price
    ServiceUpdate:
      type: object
      properties:
        name:
          type: string
        price:
          type: number
        #location:
        #  type: string
        comment:
          type: string
        dynamicPrices:
          type: array
          items:
            $ref: './dynamic_price.yaml#/components/schemas/DynamicPriceCreateUpdate'
